<?php

require_once __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/../bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

echo "🧪 Testing Microservice-Only System (No Fallback)\n";
echo "===============================================\n\n";

$service = app(\App\Services\AIPresentationService::class);

// Test 1: Check microservice availability
echo "1. Checking microservice availability...\n";
$isAvailable = $service->isMicroserviceAvailable();
echo "   Microservice available: " . ($isAvailable ? 'YES' : 'NO') . "\n";

if (!$isAvailable) {
    echo "   ❌ Microservice not available - system will return 503 error\n";
    echo "   ✅ This is the expected behavior (no fallback to Python script)\n";
} else {
    echo "   ✅ Microservice available - system will use microservice\n";
}

// Test 2: Check available methods
echo "\n2. Checking available PowerPoint generation methods...\n";
$reflection = new ReflectionClass($service);
$methods = $reflection->getMethods(ReflectionMethod::IS_PUBLIC);
$powerPointMethods = array_filter($methods, function($method) {
    return strpos($method->getName(), 'PowerPoint') !== false;
});

echo "   Available PowerPoint methods:\n";
foreach ($powerPointMethods as $method) {
    echo "   - " . $method->getName() . "()\n";
}

// Check if the old Python script method exists
$hasPythonMethod = false;
foreach ($powerPointMethods as $method) {
    if ($method->getName() === 'generatePowerPoint') {
        $hasPythonMethod = true;
        break;
    }
}

if ($hasPythonMethod) {
    echo "   ⚠️  Old generatePowerPoint() method still exists\n";
} else {
    echo "   ✅ Old generatePowerPoint() method has been removed\n";
}

// Test 3: Test PowerPoint generation (if microservice is available)
if ($isAvailable) {
    echo "\n3. Testing PowerPoint generation with microservice...\n";
    
    $templateData = [
        'template' => 'corporate_blue',
        'color_scheme' => 'blue',
        'font_style' => 'modern'
    ];
    
    $userId = 1;
    $aiResultId = 147; // Use recent presentation with content
    
    try {
        $result = $service->generatePowerPointWithMicroservice($aiResultId, $templateData, $userId);
        
        if ($result['success']) {
            echo "   ✅ PowerPoint generation successful\n";
            echo "   📁 File: " . basename($result['data']['powerpoint_file']) . "\n";
            echo "   📊 Download URL: " . $result['data']['download_url'] . "\n";
            
            // Check if file exists
            if (file_exists($result['data']['powerpoint_file'])) {
                $fileSize = filesize($result['data']['powerpoint_file']);
                echo "   📊 File size: " . number_format($fileSize) . " bytes\n";
                
                if ($fileSize > 30000) {
                    echo "   ✅ File size indicates content was included\n";
                } else {
                    echo "   ⚠️  File size suggests only outline was included\n";
                }
            }
            
            // Check the database to see if it was marked as generated by microservice
            $aiResult = \App\Models\AIResult::find($aiResultId);
            if ($aiResult && isset($aiResult->metadata['generated_by'])) {
                echo "   📝 Generated by: " . $aiResult->metadata['generated_by'] . "\n";
            }
            
        } else {
            echo "   ❌ PowerPoint generation failed: " . ($result['error'] ?? 'Unknown error') . "\n";
        }
        
    } catch (Exception $e) {
        echo "   ❌ Exception: " . $e->getMessage() . "\n";
    }
} else {
    echo "\n3. Skipping PowerPoint generation test (microservice not available)\n";
}

echo "\n📋 Summary:\n";
echo "===========\n";
echo "✅ System now uses ONLY the FastAPI microservice for PowerPoint generation\n";
echo "✅ No fallback to direct Python script\n";
echo "✅ If microservice is unavailable, system returns 503 error\n";
echo "✅ Old Python script methods have been removed\n";

?>
