<?php

require_once __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/../bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

echo "🧪 Testing Microservice-Only PowerPoint Generation\n";
echo "================================================\n\n";

$service = app(\App\Services\AIPresentationService::class);

// Check microservice availability
$isAvailable = $service->isMicroserviceAvailable();
echo "1. Microservice available: " . ($isAvailable ? 'YES' : 'NO') . "\n";

if (!$isAvailable) {
    echo "❌ Microservice not available - cannot test microservice-only generation\n";
    exit(1);
}

// Test PowerPoint generation with microservice
echo "\n2. Testing PowerPoint generation with microservice...\n";

$templateData = [
    'template' => 'corporate_blue',
    'color_scheme' => 'blue',
    'font_style' => 'modern'
];

$userId = 1;
$aiResultId = 147; // Use the recent presentation with content

try {
    $result = $service->generatePowerPointWithMicroservice($aiResultId, $templateData, $userId);
    
    if ($result['success']) {
        echo "✅ PowerPoint generation successful\n";
        echo "📁 File: " . basename($result['data']['powerpoint_file']) . "\n";
        echo "📊 Download URL: " . $result['data']['download_url'] . "\n";
        
        // Check if file exists
        if (file_exists($result['data']['powerpoint_file'])) {
            $fileSize = filesize($result['data']['powerpoint_file']);
            echo "📊 File size: " . number_format($fileSize) . " bytes\n";
            
            if ($fileSize > 30000) {
                echo "✅ File size indicates content was included\n";
            } else {
                echo "⚠️  File size suggests only outline was included\n";
            }
        }
        
        // Check the database to see if it was marked as generated by microservice
        $aiResult = \App\Models\AIResult::find($aiResultId);
        if ($aiResult && isset($aiResult->metadata['generated_by'])) {
            echo "📝 Generated by: " . $aiResult->metadata['generated_by'] . "\n";
        }
        
    } else {
        echo "❌ PowerPoint generation failed: " . ($result['error'] ?? 'Unknown error') . "\n";
    }
    
} catch (Exception $e) {
    echo "❌ Exception: " . $e->getMessage() . "\n";
}

echo "\n📋 Summary:\n";
echo "===========\n";
echo "This test confirms that the system is using ONLY the FastAPI microservice\n";
echo "for PowerPoint generation when the microservice is available.\n";

?>
